CREATE TABLE Owners (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	Bio NVARCHAR(MAX),
	NPIPID NVARCHAR(7)
)

CREATE TABLE Breeds (
Id INT IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE Chickens (
Id INT IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
Bio NVARCHAR(MAX),
ImageURL NVARCHAR(MAX),
OwnerId INT FOREIGN KEY REFERENCES Owners(Id)

)

CREATE TABLE ChickensBreeds (
ChickenId INT FOREIGN KEY REFERENCES Chickens(Id),
BreedId INT FOREIGN KEY REFERENCES Breeds(Id)

CONSTRAINT PK_CHICKENS_BREEDS PRIMARY KEY (ChickenId, BreedId)
)